# Generated by Django 5.2.4 on 2025-07-25 02:59

import django.db.models.deletion
import pistola_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('code', models.CharField(editable=False, max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('RUT', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NA', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(validators=[pistola_app.models.validate_code])),
                ('code', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pistola_app.kind')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pistola_app.object')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pistola_app.person')),
            ],
        ),
    ]
