# Generated by Django 5.2.4 on 2025-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistola_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
