# Generated by Django 5.2.4 on 2025-07-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistola_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pistola_app.kind'),
        ),
    ]
