# Generated by Django 5.2.4 on 2025-07-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistola_app', '0002_kind_alter_object_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
